{% set version = "0.3.6" %}

package:
  name: dill
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dill/dill-{{ version }}.tar.gz
  sha256: e5db55f3687856d8fbdab002ed78544e1c4559a130302693d839dfe8f93f2373

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - dill
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.cacr.caltech.edu/~mmckerns/dill.htm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Serialize all of python (almost)
  description: |
    Dill extends Python's 'pickle' module for serializing and
    de-serializing Python objects to he majority of the built-in python
    types.
  doc_url: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill.html
  doc_source_url: https://github.com/uqfoundation/dill/blob/master/README.md
  dev_url: https://github.com/uqfoundation/dill

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
