{% set name = "dill" %}
{% set version = "0.4.0" %}

package:
  name: dill
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dill-{{ version }}.tar.gz
  sha256: 0633f1d2df477324f53a895b02c901fb961bdbf65a17122586ea7019292cbcf0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  imports:
    - dill
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uqfoundation/dill
  summary: serialize all of Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    `dill` extends Python's `pickle` module for serializing and
    de-serializing Python objects to the majority of the built-in
    Python types.
  doc_url: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill.html
  dev_url: https://github.com/uqfoundation/dill

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
