schema_version: 1

context:
  name: dill
  version: "0.4.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 0633f1d2df477324f53a895b02c901fb961bdbf65a17122586ea7019292cbcf0

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=42
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - dill
      pip_check: true

about:
  homepage: https://github.com/uqfoundation/dill
  summary: serialize all of Python
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    `dill` extends Python's `pickle` module for serializing and
    de-serializing Python objects to the majority of the built-in
    Python types.
  documentation: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill.html
  repository: https://github.com/uqfoundation/dill

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
