appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: D5fEx4AoCnSoHF7kF+ggpX4z5MnRasBO91qiwX9cgZXCtqOyqoulLBXtt0qPat/CfZQdCjkEn9eHtOb506SfJpKY9i5I9VzhC/oDTcnsRClkeOCI4Ai8KN5TU6fFL5b/tyWnMg3CyxjqC9mLdvF8anuHxZKi+L+OaErE1PRKlnz7rpMZuiWP8BHQDrtaB63SNAMY3D6VgOBMx/E7tv2RPzk1pt998FLG9rto/yoGpU+gRcnCzzmlKYHxs09856/hjsdg4OuxHz707MptNz3kByusq2oJq23rZfG2gDvlQN9zATRmN8+cvYW+BmGBpHjQCR+RQsoah3kyvnX16ahCE64ERQqEBWniWKzEzm8s0hWidnVuFl9RuIfepv39HYqwARyF7Dm3+C2LpU7oGtrVzVqmllxw4O9uIPK0LfMErpqTH0SBOC+K6jOkYaZVGlLvfPuDjGbagFm957MgP5poHcqtwwn15V6k8bEv3MVgGyK64GUps7fa5H1rdkHdowjwjh4xSKt/xUJ4lqe0dpG8A6RW1TMbYJ9tp/xodomLgVImiSBpvmSPpmHxK2vIgsH8yi2YoaiNO6VAUouJqCePLsZjBz/Qqkn8bgziEeSs0gFEYygSMQRWB0vMj8M2BSTPosFkfCz7NloOsJxDyTh8HHnRNkeGoq1+93E94S8mTRw=}
conda_forge_output_validation: true
bot:
  automerge: true
conda_build:
  pkg_format: '2'
